rango/urls.py
from django.urls import path
from rango import views

app_name = 'rango'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('category/<slug:category_name_slug>/', views.show_category, name='show_category'),
    path('add_category/', views.add_category, name='add_category'),
    path('category/<slug:category_name_slug>/add_page/', views.add_page, name='add_page'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('restricted/', views.restricted, name='restricted'),
    path('logout/', views.user_logout, name='logout'),
]

tango_with_django_project/urls.py
from django.conf import settings
from django.conf.urls.static import static

"""tango_with_django_project URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path
from django.urls import include
from rango import views

urlpatterns = [
    path('', views.index, name='index'),
    path('rango/', include('rango.urls')),
    #above maps any URLs starting with rango/ to be handled by rango
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rango/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User

class Category(models.Model):
	name = models.CharField(max_length=128, unique = True)
	views = models.IntegerField(default=0)
	likes = models.IntegerField(default=0)
	slug = models.SlugField(unique=True)

	def save(self, *args, **kwargs):
		self.slug = slugify(self.name)
		super(Category, self).save(*args, **kwargs)

	class Meta:
		verbose_name_plural = 'Categories'
	
	def __str__(self):
		return self.name

class Page(models.Model):
	category = models.ForeignKey(Category, on_delete=models.CASCADE)
	title = models.CharField(max_length=128)
	url = models.URLField()
	views = models.IntegerField(default=0)

	def __str__(self):
		return self.title

class UserProfile(models.Model):
	#line is required, links UserProfile to a user model instance
	user = models.OneToOneField(User, on_delete=models.CASCADE)

	#additional attributes
	website = models.URLField(blank=True)
	picture = models.ImageField(upload_to='profile_images', blank=True)

	def __str__(self):
		return self.user.username

rango/forms.py
from django import forms
from rango.models import Page, Category, UserProfile
from django.contrib.auth.models import User

class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128, help_text="Please enter the category name.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    #an inline class to provide additional info on the form
    class Meta:
        #provide an association between the ModelForm and a model
        model = Category
        fields = ('name',)

class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128, help_text="Please enter the title of the page.")
    url = forms.URLField(max_length=200, help_text="Please enter the URL of the page.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    class Meta:
        #provide an association between the ModelForm and a model
        model = Page
        #what fields do we want in the form? this way we dont need every field in model present
        #some fields may allow Null vals, we may not want to include, here we hide the FK
        #we can either exclude the category field from the form 
        #exlude = ('category,')
        #or specify the fields to include (don't include the category field).
        fields = ('title', 'url', 'views')

    def clean(self):
        cleaned_data= self.cleaned_data
        url = cleaned_data.get('url')

        #if url is not empty and doesnt start with 'http://'. then prepend 'http://'
        if url and not url.startswith('http://'):
            url=f'http://{url}'
            cleaned_data['url']= url
        
        return cleaned_data

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model=User        
        fields = ('username', 'email', 'password',)

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('website', 'picture',)
    

rango/views.py
from django.shortcuts import render
from django.http import HttpResponse
from rango.models import Category, Page
from rango.forms import CategoryForm, PageForm, UserForm, UserProfileForm
from django.shortcuts import redirect
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from datetime import datetime


def index(request):
   #query db for a list of * categories stored
   #order by no. of likes in desc order
   #retrieve only top 5/ all if <5
   #place list in context_dict which will be passed to template engine
   category_list = Category.objects.order_by('-likes')[:5]
   page_list = Page.objects.order_by('-views')[:5]
   context_dict={}
   context_dict['boldmessage']= 'Crunchy, creamy, cookie, candy, cupcake!'
   context_dict['categories'] = category_list
   context_dict['pages'] = page_list

   visitor_cookie_handler(request)
   #obtain response obj. early so we can add cookie info
   return render(request, 'rango/index.html', context=context_dict)

def get_server_side_cookie(request, cookie, default_val=None):
   val = request.session.get(cookie)
   if not val:
      val = default_val
   return val

def visitor_cookie_handler(request):
   #get no. of visits to site
   #use COOOKIES.get() to obtain visits cookies
   #if cookie exists, val casted to an int, if not default val 1 used
   visits = int(get_server_side_cookie(request, 'visits', '1'))
   last_visit_cookie = get_server_side_cookie(request, 'last_visit', str(datetime.now()))
   last_visit_time = datetime.strptime(last_visit_cookie, '%Y-%m-%d %H:%M:%S.%f')

   #if its been more than a day since last visit
   if (datetime.now() - last_visit_time).days >0:
      visits = visits+1
      #update last visit cookie now we have updated count
      request.session['last_visit'] = str(datetime.now())
   else:
      #set last visit cookie
      request.session['last_visit'] = last_visit_cookie
   #update/set visits cookie
   request.session['visits'] = visits

def about(request):
    #create dict to pass to template engine as context.
    context_dict = {}
    visitor_cookie_handler(request)
    context_dict['visits'] = request.session['visits']

    #make use of shortcut func. to return rendered response to client.
    #first parameter is the template.
    return render(request, 'rango/about.html', context=context_dict)

def show_category(request, category_name_slug):
   #context dict to pass to rendering enging
   context_dict={}
   try:
      #can we find a category name slug with the given name?
      #if we cant the .get() method raises a DoesNotExist exception
      #the .get() method returns one model instance or raises an exception
      category = Category.objects.get(slug=category_name_slug)

      #retrieve all associated pages
      #filter() will return a list of  page objects or an empty list
      pages=Page.objects.filter(category=category)

      #adds our results list to template context under names page
      context_dict['pages']=pages
      #also add category obj. from db to context dict.
      context_dict['category']=category
   except Category.DoesNotExist:
      #enter here if specified category not found
      #template displays no category message
      context_dict['category']=None
      context_dict['pages']=None 
   return render(request, 'rango/category.html', context=context_dict)

@login_required
def add_category(request):
   form=CategoryForm()

   #A HTTP POST?
   if request.method== 'POST':
      form=CategoryForm(request.POST)

      #Have we been provided with a valid form?
      if form.is_valid():
         #save the new category to the db
         form.save(commit=True)
         #Now that the category is saved, we could confirm this
         #for now just redirect the user back to index view
         return redirect('/rango/')
      else:
         #supplied form contains errors, print them to terminal
         print(form.errors)
   #will handle the bad form, new form, or no for, supplied cases
   #render form with error messages if any
   return render(request, 'rango/add_category.html', {'form':form})

@login_required
def add_page(request, category_name_slug):
   try:
      category=Category.objects.get(slug=category_name_slug)
   except Category.DoesNotExist:
      category = None
   
   #you cannot add a page to a category that doesnt exist
   if category is None:
      return redirect('/rango/')



   form = PageForm()

   if request.method == 'POST':
      form = PageForm(request.POST)

      if form.is_valid():
         if category:
            page = form.save(commit=False)
            page.category = category
            page.views = 0
            page.save()

            return redirect(reverse('rango:show_category', kwargs={'category_name_slug':category_name_slug}))
      else:
         print(form.errors)
   context_dict={'form':form, 'category':category}
   return render(request, 'rango/add_page.html', context=context_dict)

def register(request):
   #bool val. for telling template whether reg. was successful
   #initially false, change to true when reg. succeeds
   registered=False

   #if its a HTTP POST we're interested in processing form data
   if request.method == 'POST':
      #try to grab info  from raw form info
      user_form = UserForm(request.POST)
      profile_form = UserProfileForm(request.POST)

      #if both forms are valid
      if user_form.is_valid() and profile_form.is_valid():
         #save form data to db
         user = user_form.save()

         # hash password and update user object
         user.set_password(user.password)
         user.save()

         #sorting UserProfile instance, set commit=false to delay saving model until its ready
         profile = profile_form.save(commit=False)
         profile.user = user

         #if user provided profile pic, get from form and put in model
         if 'picture' in request.FILES:
            profile.picture = request.FILES['picture']

         #now save UserProfile instance
         profile.save()

         #update variable to indicate reg. was success
         registered = True
      else:
         #invalid form(s) or mistakes, print problems to terminal
         print(user_form.errors, profile_form.errors)
   else:
      #not a HTTP POST, sp render form using 2 ModelForm instances
      #these will be blank and ready for user input
      user_form = UserForm()
      profile_form = UserProfileForm()

   #render template depending on context
   return render(request, 'rango/register.html', context={'user_form':user_form, 'profile_form':profile_form, 'registered':registered})

def user_login(request):
   #if request is HTTP POST, try get relevant info
   if request.method=='POST':
      #retrieve username and password, obtained from login form
      #using request.POST.get('<var>') instead of request.POST['<var>']
      #as first returns None is val doesnt exist, while latter will raise KeyError excep.
      username = request.POST.get('username')
      password = request.POST.get('password')

      #use djangos machinery to see if combo is valid, a user object
      #will be returned if it is
      user = authenticate(username=username, password=password)

      #if we have a user object, details correct, if None no user match
      if user:
         #is account active or has it been disabled
         if user.is_active:
            #if account valid and active log in, go back to homepage
            login(request, user)
            return redirect(reverse('rango:index'))
         else:
            #account inactive, dont log in
            return HttpResponse("Your Rango account is diabled.")
      else:
         #incorrect login details, dont login
         print(f"Invalid login details: {username}, {password}")
         return HttpResponse("Invalid login details supplied.")
   #request is not a HTTP POST, so display login form - most likely a HTTP GET
   else:
      #no context  variables to pass the template system, hence blank dic. obj.
      return render(request, 'rango/login.html')

@login_required
def restricted(request):
   return render(request, 'rango/restricted.html')

#login_required() decorator ensures only those logged in can access this view
@login_required
def user_logout(request):
   logout(request)
   #return to homepage
   return redirect(reverse('rango:index'))

templates/rango/about.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
	About Rango
{% endblock %}
{% block body_block %}
		<h1>Rango says...</h1>
		<div>
			here is the about page <br />
			<strong>This tutorial has been put together by mel.</strong><br />
			<p>Visits: {{visits }}</p>
		</div>
		<div>
			<a href="/rango/">Index</a><br />
			<img src="{% static 'images/rango.jpg' %}"
				alt="Picture of Rango" /> <!-- New Line -->
			<img src="{{ MEDIA_URL }}cat.jpg"
				alt="Picture of a cat" /> <!-- New Line -->
		</div>
{% endblock %}

templates/rango/add_category.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
	Add a Category
{% endblock %}
{% block body_block %}

        <h1>Add a Category</h1>
        <div>
            {% if user.is_authenticated %}
            <form id="category_form" method="post" action="{% url 'rango:add_category' %}">
                {% csrf_token %}
                {% for hidden in form.hidden_fields %}
                    {{ hidden }}
                {% endfor %}
                {% for field in form.visible_fields %}
                    {{ field.errors }}
                    {{ field.help_text }}
                    {{ field }}
                {% endfor %}
                <input type="submit" name="submit" value="Create Category" />
            </form>
            {% else %}
            <a href="{% url 'rango:index' %}">Return to the homepage.</a><br />

            {% endif %}
        </div>
{% endblock %}

templates/rango/add_page.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
	Add a Page
{% endblock %}
{% block body_block %}
    {% if user.is_authenticated %}
        <h1>Add a Page to {{ category.name }}</h1>
        <div>
            <form id="page_form" method="post" action="{% url 'rango:add_page' category.slug %}">
                {% csrf_token %}
                {% for hidden in form.hidden_fields %}
                    {{ hidden }}
                {% endfor %}
                {% for field in form.visible_fields %}
                    {{ field.errors }}
                    {{ field.help_text }}
                    {{ field }}
                {% endfor %}
                <input type="submit" name="submit" value="Add Page" />
            </form>
        </div>
    {% else %}
    <a href="{% url 'rango:index' %}">Return to the homepage.</a><br />
    {% endif %}
{% endblock %}

templates/rango/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load rango_template_tags %}

<html>
    <head lang="en">
        <meta charset="UTF-8" />
        <title>
            Rango -
            {% block title_block %}
            How to Tango with Django!
            {% endblock %}
        </title>
    </head>
    <body>
        <div>
        {% block body_block %}
        {% endblock %}
        </div>
        <div>
            {% block sidebar_block %}
                {% get_category_list category %}
            {% endblock %}
        </div>
        <hr />
        <div>
            <ul>
            {% if user.is_authenticated %}
                <!-- show these when user logged in-->
                <li><a href="{% url 'rango:add_category' %}">Add a New Category</a></li>
                <li><a href="{% url 'rango:restricted' %}">Restricted Page</a></li>
                <li><a href="{% url 'rango:logout' %}">Logout</a></li>
            {% else %}
                <!-- show when user not logged in-->
                <li><a href="{% url 'rango:register' %}">Sign Up</a></li>
                <li><a href="{% url 'rango:login' %}">Login</a></li>
            {% endif %}
                <!--always show-->
                <li><a href="{% url 'rango:about' %}">About</a></li>
                <li><a href="{% url 'rango:index' %}">Index</a></li>
            </ul>
        </div>
    </body>
</html>

templates/rango/categories.html
<ul>
{% if categories %}
    {% for c in categories %}
        {% if c == current_category %}
        <li><strong><a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a></strong></li>
        {% else %}
        <li><a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a></li>
        {% endif %}
    {% endfor %}
{% else %}
    <li><strong>There are no categories present.</strong></li>
{% endif %}
</ul>

templates/rango/category.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    {% if category %}
        {{ category.name }}
    {% else %}
        Unkown Category
    {% endif %}
{% endblock %}

{% block body_block %}
    {% if category %}
        <h1>{{ category.name }}</h1>
        {% if pages %}
        <ul>
            {% for page in pages %}
            <li><a href="{{page.url }}">{{ page.title }}</a></li>
            {% endfor %}
        </ul>
        {% else %}
        <strong>No pages currently in category</strong>
        {% endif %}

    {% if user.is_authenticated %}
    <a href="/rango/category/{{category.slug }}/add_page/">Add Page</a> <br/>
    {% else %}
        Only logged in users can add pages.
        <a href="{% url 'rango:index' %}">Return to the homepage.</a><br />

    {% endif %}
    {% else %}
        The specified category does not exist.
    {% endif %}
{% endblock %}

templates/rango/index.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
	Homepage
{% endblock %}
{% block body_block %}
		<h1>Rango says...</h1>
		<div>
			{% if user.is_authenticated %}
			howdy {{ user.username }}!
			{% else %}
			hey there partner! <br />
			{% endif %}
			<strong>{{ boldmessage }}</strong>
		</div>
		<div>
			{% if categories %}
				<ul>
					{% for category in categories %}
					<li>
						<a href="{% url 'rango:show_category' category.slug %}">{{category.name}}</a></li>
					{% endfor %}
				</ul>
			{% endif %}
			</div>
			<div>
				{% if categories %}
				<h2>Most liked Categories</h2>
				<ul>
					{% for category in categories %}
					<li><a href="{% url 'rango:show_category' category.slug %}">{{category.name}}</a></li>
					{% endfor %}
				</ul>
			{% endif %}
			</div>
			<div>
				{% if pages %}
				<h2>Most Viewed Pages</h2>
				<ul>
					{% for page in pages %}
					<li><a href="{{page.url }}">{{page.title}}</a></li>
					{% endfor %}
				</ul>
				{% else %}
				<strong>There are no pages present.</strong>
				{% endif %}
				</ul>
			</div>
			<div>
			<img src="{% static 'images/rango.jpg' %}"
				alt="Picture of Rango" /> <!-- New Line -->
		</div>
{% endblock %}

templates/rango/login.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Login
{% endblock %}

{% block body_block %}
<h1>Login to Rango</h1>
<form id="login_form" method="post" action="{% url 'rango:login' %}">
    {% csrf_token %}
    Username: <input type="text" name="username" value="" size="50" />
    <br />
    Password: <input type="password" name="password" value="" size="50" />
    <br />
    <input type="submit" value="submit" />
</form>
{% endblock %}

templates/rango/register.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Register
{% endblock %}

{% block body_block %}
<h1>Register for Rango</h1>
{% if registered %}
Rango says: <strong>thank you for registering!</strong>
<a href="{% url 'rango:index' %}">Return to the homepage.</a><br />
{% else %}
Rango says: <strong>register here!</strong><br />
<form id="user_form" method="post" action="{% url 'rango:register' %}" enctype="multipart/form-data">
    {% csrf_token %}

    <!-- display each form-->
    {{ user_form.as_p }}
    {{ profile_form.as_p }} 

    <input type="submit" name="submit" value="Register" />
</form>
{% endif %}
{% endblock %}

templates/rango/restricted.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Restricted Page
{% endblock %}
{% block body_block %}
Since you're logged in, you can see this!
{% endblock %}